# Generated by Django 6.0.5 on 2026-05-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
