# Generated by Django 6.0.5 on 2026-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
